import type { Metadata } from "next";
import "./globals.css";
import Notification from "@/components/Notification";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import AuthProvider from "@/components/AuthProvider";
import QueryProvider from "@/components/QueryProvider";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "kaltdigi-restaurant-food",
  description: "Generated by Mehrdad",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <AuthProvider>
        <QueryProvider>
          <body className={` antialiased`}>
            <Notification />
            <Navbar />
            {children}
            <Footer />
            <ToastContainer
              position="bottom-right"
              theme="dark"
              autoClose={3000}
            />
          </body>
        </QueryProvider>
      </AuthProvider>
    </html>
  );
}
